spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: aa
    username: aa
    password: 1111

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    defer-datasource-initialization: true